### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by flber** [subsoap/fps#1]
I just saw this repo and thought it would be interesting to check out (as there seems to be very little documentation on how 3d games work in defold), but it doesn't seem to work for me. Is this still in development, or is it outdated now?
Also, when I say it doesn't work, I mean that nothing loads or runs. Everything looks empty, with lots of `java.lang.NullPointerException: Unknown.` errors. 
Thanks for the help!

**Comment by subsoap** [comment]
This example is outdated, I'm not sure why that error happened though, which OS are you on?

I'll be publishing a new fresh reworked FPS version sometime in the future along with more 3D specific resources for Defold so keep an eye out for that.

**Comment by flber** [comment]
I'm on windows 10 64 bit. 
I would absolutely love to see a new FPS example, so thank you for the help!

**Comment by subsoap** [comment]
I just tested this example on my Win10 install and it did run fine. What is your computer's hardware? Graphics drivers all up to date?

**Comment by flber** [comment]
There we go. I restarted my computer and it now works! Though I do have a weird problem where maybe every other time it throws a `java.net.SocketTimeoutException: connect timed out` error and crashes, but eh.

**Comment by subsoap** [comment]
Do other projects cause that issue? Would be something worth posting on the official forums to investigate.

**Comment by flber** [comment]
Yeah, all other projects have the same problem. I've made a new issue on the repo, but I suppose I could also post something on the forums.
